/**
 * Comprehensive Force Exercises Expansion - Part 2
 *
 * Additional 600+ exercises with detailed variations
 * To be integrated into seed-exercises-comprehensive.ts
 */

export const CHEST_VARIATIONS_EXTENDED = [
  // BARBELL VARIATIONS
  {
    name: 'Reverse Grip Bench Press',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Développé couché prise inversée',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux', 'Triceps'],
    secondary_muscles: ['Deltoïdes'],
    equipment: ['Barre olympique', 'Banc'],
    coaching_cues: ['Prise supination', 'Coudes près corps', 'Contrôle strict'],
    common_mistakes: ['Prise trop large', 'Manque contrôle', 'Arquer excessif'],
    safety_notes: ['Moins lourd que classique', 'Focus partie haute pectoraux'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 6,
    typical_reps_max: 10,
    typical_rest_sec: 120,
    technical_complexity: 7,
    injury_risk: 'moderate',
    is_validated: true,
    illustration_priority: 6,
  },
  {
    name: 'Incline Barbell Bench Press 30°',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Développé incliné 30 degrés',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux'],
    secondary_muscles: ['Deltoïdes', 'Triceps'],
    equipment: ['Barre olympique', 'Banc incliné'],
    coaching_cues: ['Angle 30°', 'Barre vers haut poitrine', 'Descente contrôlée'],
    common_mistakes: ['Angle trop prononcé', 'Rebond', 'ROM partiel'],
    safety_notes: ['Excellent partie haute', 'Angle optimal 30°'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 5,
    typical_reps_min: 6,
    typical_reps_max: 10,
    typical_rest_sec: 150,
    technical_complexity: 6,
    injury_risk: 'moderate',
    is_validated: true,
    illustration_priority: 8,
  },
  {
    name: 'Paused Bench Press',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'advanced',
    description_short: 'Développé couché avec pause',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux', 'Triceps'],
    secondary_muscles: ['Deltoïdes'],
    equipment: ['Barre olympique', 'Banc'],
    coaching_cues: ['Pause 2-3 sec poitrine', 'Pas de rebond', 'Explosion montée'],
    common_mistakes: ['Rebond malgré pause', 'Perte tension', 'Arquer excessif'],
    safety_notes: ['Excellent technique', 'Moins lourd que standard'],
    target_goals: ['strength'],
    typical_sets_min: 3,
    typical_sets_max: 5,
    typical_reps_min: 3,
    typical_reps_max: 6,
    typical_rest_sec: 180,
    technical_complexity: 8,
    injury_risk: 'moderate',
    is_validated: true,
    illustration_priority: 7,
  },

  // DUMBBELL VARIATIONS
  {
    name: 'Neutral Grip Dumbbell Press',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'beginner',
    description_short: 'Développé haltères prise neutre',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux', 'Triceps'],
    secondary_muscles: ['Deltoïdes'],
    equipment: ['Haltères', 'Banc'],
    coaching_cues: ['Paumes face à face', 'Coudes près corps', 'ROM complète'],
    common_mistakes: ['Rotation poignets', 'ROM partiel', 'Instabilité'],
    safety_notes: ['Moins stress épaules', 'Bon pour débutants'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 8,
    typical_reps_max: 12,
    typical_rest_sec: 120,
    technical_complexity: 4,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 7,
  },
  {
    name: 'Incline Dumbbell Fly',
    discipline: 'force',
    category: 'isolation',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Écarté incliné haltères',
    movement_pattern: 'fly',
    primary_muscles: ['Pectoraux'],
    equipment: ['Haltères', 'Banc incliné'],
    coaching_cues: ['30-45° inclinaison', 'Arc de cercle', 'Stretch contrôlé'],
    common_mistakes: ['Trop lourd', 'Coudes tendus', 'ROM excessive'],
    safety_notes: ['Stretch important', 'Progression prudente'],
    target_goals: ['hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 10,
    typical_reps_max: 15,
    typical_rest_sec: 90,
    technical_complexity: 6,
    injury_risk: 'moderate',
    is_validated: true,
    illustration_priority: 7,
  },
  {
    name: 'Decline Dumbbell Fly',
    discipline: 'force',
    category: 'isolation',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Écarté décliné haltères',
    movement_pattern: 'fly',
    primary_muscles: ['Pectoraux'],
    equipment: ['Haltères', 'Banc'],
    coaching_cues: ['15-30° déclinaison', 'Arc de cercle', 'Squeeze en haut'],
    common_mistakes: ['Angle trop prononcé', 'ROM excessive', 'Trop lourd'],
    safety_notes: ['Focus partie basse', 'Durée limitée'],
    target_goals: ['hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 10,
    typical_reps_max: 15,
    typical_rest_sec: 90,
    technical_complexity: 6,
    injury_risk: 'moderate',
    is_validated: true,
    illustration_priority: 6,
  },

  // CABLE VARIATIONS
  {
    name: 'Cable Crossover High to Low',
    discipline: 'force',
    category: 'isolation',
    subcategory: 'chest',
    difficulty: 'beginner',
    description_short: 'Crossover cable haut vers bas',
    movement_pattern: 'fly',
    primary_muscles: ['Pectoraux'],
    equipment: ['Cable crossover'],
    coaching_cues: ['Poulies hautes', 'Arc vers bas', 'Squeeze milieu'],
    common_mistakes: ['Bras tendus', 'Trop de momentum', 'ROM partiel'],
    safety_notes: ['Excellent isolation', 'Tension constante'],
    target_goals: ['hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 12,
    typical_reps_max: 20,
    typical_rest_sec: 75,
    technical_complexity: 4,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 8,
  },
  {
    name: 'Cable Crossover Low to High',
    discipline: 'force',
    category: 'isolation',
    subcategory: 'chest',
    difficulty: 'beginner',
    description_short: 'Crossover cable bas vers haut',
    movement_pattern: 'fly',
    primary_muscles: ['Pectoraux'],
    equipment: ['Cable crossover'],
    coaching_cues: ['Poulies basses', 'Arc vers haut', 'Focus partie haute'],
    common_mistakes: ['Bras tendus', 'Momentum', 'ROM partiel'],
    safety_notes: ['Excellent partie haute pectoraux'],
    target_goals: ['hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 12,
    typical_reps_max: 20,
    typical_rest_sec: 75,
    technical_complexity: 4,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 7,
  },
  {
    name: 'Standing Cable Press',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Développé cable debout',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux', 'Core'],
    secondary_muscles: ['Triceps', 'Deltoïdes'],
    equipment: ['Machine à câbles'],
    coaching_cues: ['Debout dos câbles', 'Presse avant', 'Core engagé'],
    common_mistakes: ['Arquer dos', 'Manque stabilité', 'ROM partiel'],
    safety_notes: ['Excellent stabilisation', 'Fonctionnel'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 10,
    typical_reps_max: 15,
    typical_rest_sec: 90,
    technical_complexity: 6,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 7,
  },

  // MACHINE VARIATIONS
  {
    name: 'Hammer Strength Chest Press',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'beginner',
    description_short: 'Presse pectoraux Hammer Strength',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux', 'Triceps'],
    secondary_muscles: ['Deltoïdes'],
    equipment: ['Machine Hammer Strength'],
    coaching_cues: ['Mouvement libre guidé', 'ROM complète', 'Squeeze en haut'],
    common_mistakes: ['ROM partiel', 'Perte tension', 'Trop lourd'],
    safety_notes: ['Excellent pour volume', 'Unilatéral possible'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 8,
    typical_reps_max: 15,
    typical_rest_sec: 90,
    technical_complexity: 3,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 7,
  },
  {
    name: 'Pec Deck Machine',
    discipline: 'force',
    category: 'isolation',
    subcategory: 'chest',
    difficulty: 'beginner',
    description_short: 'Butterfly machine',
    movement_pattern: 'fly',
    primary_muscles: ['Pectoraux'],
    equipment: ['Pec Deck'],
    coaching_cues: ['Coudes légère flexion', 'Squeeze milieu', 'Contrôle descente'],
    common_mistakes: ['Bras tendus', 'ROM partiel', 'Trop lourd'],
    safety_notes: ['Excellente isolation', 'Facile apprentissage'],
    target_goals: ['hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 12,
    typical_reps_max: 20,
    typical_rest_sec: 75,
    technical_complexity: 2,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 7,
  },

  // BODYWEIGHT VARIATIONS
  {
    name: 'Wide Grip Push-up',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'beginner',
    description_short: 'Pompes prise large',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux'],
    secondary_muscles: ['Triceps', 'Deltoïdes'],
    equipment: ['Sol'],
    coaching_cues: ['Mains plus larges épaules', 'Corps aligné', 'ROM complète'],
    common_mistakes: ['Hanches basses', 'ROM partiel', 'Coudes trop évasés'],
    safety_notes: ['Focus pectoraux', 'Progression vers lesté'],
    target_goals: ['strength', 'hypertrophy', 'endurance'],
    typical_sets_min: 3,
    typical_sets_max: 5,
    typical_reps_min: 10,
    typical_reps_max: 30,
    typical_rest_sec: 90,
    technical_complexity: 3,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 8,
  },
  {
    name: 'Diamond Push-up',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Pompes diamant mains jointes',
    movement_pattern: 'push',
    primary_muscles: ['Triceps', 'Pectoraux'],
    equipment: ['Sol'],
    coaching_cues: ['Mains diamant sous poitrine', 'Coudes près corps', 'ROM complète'],
    common_mistakes: ['Coudes évasés', 'ROM partiel', 'Hanches basses'],
    safety_notes: ['Focus triceps', 'Excellent poids corps'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 8,
    typical_reps_max: 15,
    typical_rest_sec: 90,
    technical_complexity: 5,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 8,
  },
  {
    name: 'Decline Push-up',
    discipline: 'force',
    category: 'compound',
    subcategory: 'chest',
    difficulty: 'intermediate',
    description_short: 'Pompes pieds surélevés',
    movement_pattern: 'push',
    primary_muscles: ['Pectoraux'],
    secondary_muscles: ['Deltoïdes', 'Triceps'],
    equipment: ['Banc', 'Box'],
    coaching_cues: ['Pieds sur banc', 'Corps aligné', 'ROM complète'],
    common_mistakes: ['Hanches basses', 'ROM partiel', 'Trop haut'],
    safety_notes: ['Focus partie haute pectoraux'],
    target_goals: ['strength', 'hypertrophy'],
    typical_sets_min: 3,
    typical_sets_max: 4,
    typical_reps_min: 10,
    typical_reps_max: 20,
    typical_rest_sec: 90,
    technical_complexity: 4,
    injury_risk: 'low',
    is_validated: true,
    illustration_priority: 7,
  },
];

// Note: This file contains the first 15 of 600+ additional exercises
// Continue building similar comprehensive arrays for:
// - BACK_VARIATIONS_EXTENDED (50+ exercises)
// - SHOULDERS_VARIATIONS_EXTENDED (40+ exercises)
// - ARMS_VARIATIONS_EXTENDED (30+ exercises)
// - LEGS_VARIATIONS_EXTENDED (80+ exercises)
// - CORE_VARIATIONS_EXTENDED (40+ exercises)
// - FULL_BODY_VARIATIONS_EXTENDED (30+ exercises)
