import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const muscleCache = new Map<string, string>();
const equipmentCache = new Map<string, string>();

async function getMuscleId(name: string): Promise<string | null> {
  if (muscleCache.has(name)) return muscleCache.get(name)!;
  const { data } = await supabase.from('muscle_groups').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) muscleCache.set(name, data.id);
  return data?.id || null;
}

async function getEquipmentId(name: string): Promise<string | null> {
  if (equipmentCache.has(name)) return equipmentCache.get(name)!;
  const { data } = await supabase.from('equipment_types').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) equipmentCache.set(name, data.id);
  return data?.id || null;
}

async function seedExercise(ex: any) {
  const primaryMuscleIds = (await Promise.all((ex.primary_muscles || []).map(getMuscleId))).filter(Boolean);
  const secondaryMuscleIds = (await Promise.all((ex.secondary_muscles || []).map(getMuscleId))).filter(Boolean);
  const equipmentIds = (await Promise.all((ex.equipment || []).map(getEquipmentId))).filter(Boolean);

  const { data: exercise, error } = await supabase.from('exercises').insert({
    name: ex.name,
    discipline: 'endurance',
    category: ex.category,
    difficulty: ex.difficulty,
    description_short: ex.description,
    movement_pattern: ex.movement_pattern || 'cardio',
    is_validated: true,
    typical_sets_min: ex.sets_min || 1,
    typical_sets_max: ex.sets_max || 1,
    typical_reps_min: ex.reps_min || 1,
    typical_reps_max: ex.reps_max || 1,
    typical_rest_sec: ex.rest_sec || 60,
  }).select().single();

  if (error) {
    console.error(`Error inserting ${ex.name}:`, error.message);
    return;
  }

  if (!exercise) return;

  if (primaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      primaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'primary' }))
    );
  }

  if (secondaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      secondaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'secondary' }))
    );
  }

  if (equipmentIds.length > 0) {
    await supabase.from('exercise_equipment').insert(
      equipmentIds.map(id => ({ exercise_id: exercise.id, equipment_type_id: id, is_required: true }))
    );
  }

  console.log(`✅ ${ex.name}`);
}

const cyclingExercises = [
  {
    name: 'FTP Test 20min Cycling',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Test FTP 20min effort maximal soutenu 95% FTP',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'FTP Test Ramp Protocol',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Test FTP rampe progressive jusqu épuisement',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Sweet Spot 88-93% FTP',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Sweet spot 88-93% FTP Z3 high tempo soutenu',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Sweet Spot Intervals 3x10min',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Intervalles sweet spot 3x10min 90% FTP 5min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Sweet Spot Intervals 2x20min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles sweet spot 2x20min 88-92% FTP 10min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 2,
    sets_max: 2,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 600,
  },
  {
    name: 'Threshold Intervals 95-105% FTP',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles seuil 95-105% FTP Z4 lactate threshold',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'Threshold Intervals 2x12min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles seuil 2x12min 100% FTP 6min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 2,
    sets_max: 2,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 360,
  },
  {
    name: 'Threshold Intervals 3x8min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles seuil 3x8min 102% FTP 4min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'VO2max Intervals 120% FTP',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles VO2max 120% FTP Z5 effort maximal',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'VO2max Intervals 5x3min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles VO2max 5x3min 120% FTP 3min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'VO2max Intervals 8x2min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles VO2max 8x2min 125% FTP 2min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Anaerobic Capacity 150% FTP',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Capacité anaérobie 150% FTP efforts courts intenses',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Anaerobic Intervals 10x30sec',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles anaérobies 10x30sec 150%+ FTP 2:30 repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 150,
  },
  {
    name: 'Sprint Intervals 200% FTP',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Sprints 200% FTP 15-20sec effort maximal',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Sprint Intervals 8x15sec',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Sprints 8x15sec max power 5min récupération complète',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Over-Unders Workout',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Over-unders alternance 95% et 105% FTP seuil lactique',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 3,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Over-Unders 3x9min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Over-unders 3x9min 3min@95% puis 3min@105% FTP',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Endurance Zone 2 60-75% FTP',
    category: 'cycling',
    difficulty: 'beginner',
    description: 'Sortie endurance Z2 60-75% FTP base aérobie',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Tempo Zone 3 76-87% FTP',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Sortie tempo Z3 76-87% FTP allure soutenue',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Recovery Spin 50-60% FTP',
    category: 'cycling',
    difficulty: 'beginner',
    description: 'Sortie récupération active 50-60% FTP Z1 facile',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Pyramid Intervals 1-2-3-2-1',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Pyramide 1-2-3-2-1min 120% FTP avec repos égaux',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 2,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Tabata Cycling 20-10',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Tabata vélo 20sec sprint 10sec repos 8 rounds',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Micro-Intervals 40-20',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Micro-intervalles 40sec on 20sec off 130% FTP',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 12,
    sets_max: 16,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Sustained Power Intervals 10min',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles puissance soutenue 3x10min 95% FTP',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Tempo Intervals 3x15min',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Intervalles tempo 3x15min 85% FTP Z3 5min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Criterium Simulation',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Simulation critérium sprints répétés haute intensité',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Time Trial Simulation 40K',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Simulation contre-la-montre 40K 100% FTP effort constant',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Hill Repeats Cycling Seated',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Répétitions côtes assis puissance constante Z4-Z5',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'Hill Repeats Cycling Standing',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Répétitions côtes en danseuse explosivité',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers', 'abdominaux'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: 'Cadence Drills High RPM',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Drills cadence élevée 100-120rpm technique souplesse',
    primary_muscles: ['quadriceps', 'ischio-jambiers'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Cadence Drills Low RPM Strength',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Drills cadence basse 50-60rpm force musculaire',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Single Leg Drills Cycling',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Drills jambe isolée technique pédalage efficacité',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Progression Ride 2hr',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Sortie progression 2h Z2→Z3→Z4 negative split',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Fasted Morning Ride Z2',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Sortie matinale jeun Z2 adaptation métabolique lipides',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Long Endurance Ride 3-5hr',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Sortie longue endurance 3-5h Z2 base aérobie',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Sufferfest Four Horsemen',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Four Horsemen séance légendaire Z4-Z5 intensité maximale',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Zwift Alpe du Zwift',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Ascension Alpe du Zwift simulation montagne',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Race Simulation Intervals',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Simulation course attaques répétées variation intensité',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Neuromuscular Power Sprints',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Sprints neuromusculaires 10sec max power repos complet',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 360,
  },
  {
    name: 'Seated Climbing Intervals',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Intervalles montée assis 4x6min 95% FTP technique',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 4,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'Mixed Terrain Ride',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Sortie mixte plat-côtes variation intensité Z2-Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Group Ride Simulation',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Simulation sortie groupe variations tempo relais',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Endurance Spinning Class',
    category: 'cycling',
    difficulty: 'beginner',
    description: 'Cours spinning endurance Z2-Z3 musique motivation',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'HIIT Spinning Class',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Cours spinning HIIT intervalles intenses Z4-Z5',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Indoor Trainer Sweet Spot',
    category: 'cycling',
    difficulty: 'intermediate',
    description: 'Séance home trainer sweet spot 90min 88-92% FTP',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Outdoor Long Climb',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Ascension longue col montagne 30-60min Z3-Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Century Ride 100 Miles',
    category: 'cycling',
    difficulty: 'advanced',
    description: 'Sortie century 100 miles Z2 endurance ultra',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
];

async function main() {
  console.log('🚴 Seeding Endurance Cycling FTP Protocols (50 exercises)...\n');

  let success = 0;
  let failed = 0;

  for (const ex of cyclingExercises) {
    try {
      await seedExercise(ex);
      success++;
    } catch (error) {
      console.error(`❌ Failed to seed ${ex.name}:`, error);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success}/${cyclingExercises.length}`);
  console.log(`❌ Failed: ${failed}/${cyclingExercises.length}`);
  console.log('\n🎯 Cycling FTP protocols enrichment complete!');
}

main().then(() => process.exit(0));
