import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const muscleCache = new Map<string, string>();
const equipmentCache = new Map<string, string>();

async function getMuscleId(name: string): Promise<string | null> {
  if (muscleCache.has(name)) return muscleCache.get(name)!;
  const { data } = await supabase.from('muscle_groups').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) muscleCache.set(name, data.id);
  return data?.id || null;
}

async function getEquipmentId(name: string): Promise<string | null> {
  if (equipmentCache.has(name)) return equipmentCache.get(name)!;
  const { data } = await supabase.from('equipment_types').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) equipmentCache.set(name, data.id);
  return data?.id || null;
}

async function seedExercise(ex: any) {
  const primaryMuscleIds = (await Promise.all((ex.primary_muscles || []).map(getMuscleId))).filter(Boolean);
  const secondaryMuscleIds = (await Promise.all((ex.secondary_muscles || []).map(getMuscleId))).filter(Boolean);
  const equipmentIds = (await Promise.all((ex.equipment || []).map(getEquipmentId))).filter(Boolean);

  const { data: exercise, error } = await supabase.from('exercises').insert({
    name: ex.name,
    discipline: 'functional',
    category: ex.category,
    difficulty: ex.difficulty,
    description_short: ex.description,
    movement_pattern: ex.movement_pattern || 'compound',
    is_validated: true,
    typical_sets_min: ex.sets_min || 1,
    typical_sets_max: ex.sets_max || 1,
    typical_reps_min: ex.reps_min || 1,
    typical_reps_max: ex.reps_max || 1,
    typical_rest_sec: ex.rest_sec || 0,
  }).select().single();

  if (error) {
    console.error(`Error inserting ${ex.name}:`, error.message);
    return;
  }

  if (!exercise) return;

  if (primaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      primaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'primary' }))
    );
  }

  if (secondaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      secondaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'secondary' }))
    );
  }

  if (equipmentIds.length > 0) {
    await supabase.from('exercise_equipment').insert(
      equipmentIds.map(id => ({ exercise_id: exercise.id, equipment_type_id: id, is_required: true }))
    );
  }

  console.log(`✅ ${ex.name}`);
}

const metconFormats = [
  {
    name: 'AMRAP 10min Burpees + Box Jumps',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'AMRAP 10min 10 Burpees 15 Box Jumps maximum rounds',
    primary_muscles: ['pectoraux', 'quadriceps', 'mollets'],
    secondary_muscles: ['deltoïdes', 'fessiers', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'AMRAP 15min Thrusters + Pull-ups',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'AMRAP 15min 5 Thrusters 95lbs 10 Pull-ups maximum rounds',
    primary_muscles: ['quadriceps', 'deltoïdes', 'dorsaux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'AMRAP 20min Cindy Format',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'AMRAP 20min 5 Pull-ups 10 Push-ups 15 Squats classic Cindy',
    primary_muscles: ['dorsaux', 'pectoraux', 'quadriceps'],
    secondary_muscles: ['biceps', 'triceps', 'fessiers'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'AMRAP 12min KB Swings + Goblet Squats',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'AMRAP 12min 15 KB Swings 53lbs 12 Goblet Squats',
    primary_muscles: ['fessiers', 'quadriceps', 'ischio-jambiers'],
    secondary_muscles: ['érecteurs', 'deltoïdes'],
    equipment: ['kettlebell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'AMRAP 8min Double-Unders + Sit-ups',
    category: 'metcon_format',
    difficulty: 'beginner',
    description: 'AMRAP 8min 30 Double-Unders 20 Sit-ups cardio core',
    primary_muscles: ['mollets', 'abdominaux'],
    secondary_muscles: ['quadriceps', 'fléchisseurs hanches'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'EMOM 10min Power Cleans',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'EMOM 10min 3 Power Cleans 185lbs every minute technique strength',
    primary_muscles: ['quadriceps', 'deltoïdes', 'trapèzes'],
    secondary_muscles: ['fessiers', 'érecteurs', 'dorsaux'],
    equipment: ['barbell'],
    sets_min: 10,
    sets_max: 10,
    reps_min: 3,
    reps_max: 3,
    rest_sec: 0,
  },
  {
    name: 'EMOM 12min Alternating Movements',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'EMOM 12min Min1 10 Push-ups Min2 15 Squats Min3 10 Sit-ups repeat',
    primary_muscles: ['pectoraux', 'quadriceps', 'abdominaux'],
    secondary_muscles: ['triceps', 'fessiers', 'fléchisseurs hanches'],
    equipment: [],
    sets_min: 4,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'EMOM 15min Thruster + Burpees',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'EMOM 15min 5 Thrusters 95lbs 5 Burpees every minute high intensity',
    primary_muscles: ['quadriceps', 'deltoïdes', 'pectoraux'],
    secondary_muscles: ['fessiers', 'triceps', 'mollets'],
    equipment: ['barbell'],
    sets_min: 15,
    sets_max: 15,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'EMOM 8min Double-Unders + Box Jumps',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'EMOM 8min 20 Double-Unders 10 Box Jumps 20in plyometric',
    primary_muscles: ['mollets', 'quadriceps'],
    secondary_muscles: ['fessiers', 'ischio-jambiers'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'EMOM 20min KB Complex',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'EMOM 20min 5 KB Swings 5 Goblet Squats 5 KB Press 53lbs',
    primary_muscles: ['fessiers', 'quadriceps', 'deltoïdes'],
    secondary_muscles: ['ischio-jambiers', 'érecteurs', 'triceps'],
    equipment: ['kettlebell'],
    sets_min: 20,
    sets_max: 20,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'For Time 21-15-9 Thrusters + Chest-to-Bar',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'For Time 21-15-9 Thrusters 95lbs Chest-to-Bar Pull-ups sprint WOD',
    primary_muscles: ['quadriceps', 'deltoïdes', 'dorsaux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'For Time 50-40-30-20-10 Wall Balls + Burpees',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'For Time 50-40-30-20-10 Wall Balls 20lbs Burpees descending ladder',
    primary_muscles: ['quadriceps', 'deltoïdes', 'pectoraux'],
    secondary_muscles: ['fessiers', 'triceps', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'For Time 100-75-50-25 Double-Unders',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'For Time 100-75-50-25 Double-Unders pure cardio conditioning',
    primary_muscles: ['mollets', 'quadriceps'],
    secondary_muscles: ['deltoïdes', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'For Time 5 Rounds Row + Squats',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'For Time 5 Rounds 500m Row 20 Air Squats endurance strength',
    primary_muscles: ['quadriceps', 'dorsaux', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'For Time 3 Rounds Deadlifts + Run',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'For Time 3 Rounds 21 Deadlifts 225lbs 400m Run power endurance',
    primary_muscles: ['érecteurs', 'quadriceps', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'trapèzes'],
    equipment: ['barbell'],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Tabata 8 Rounds Air Squats',
    category: 'metcon_format',
    difficulty: 'beginner',
    description: 'Tabata 8 Rounds 20sec Air Squats 10sec rest high intensity legs',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Tabata 8 Rounds Push-ups',
    category: 'metcon_format',
    difficulty: 'beginner',
    description: 'Tabata 8 Rounds 20sec Push-ups 10sec rest upper body endurance',
    primary_muscles: ['pectoraux', 'triceps'],
    secondary_muscles: ['deltoïdes', 'abdominaux'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Tabata 8 Rounds Burpees',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Tabata 8 Rounds 20sec Burpees 10sec rest full body metabolic',
    primary_muscles: ['pectoraux', 'quadriceps', 'mollets'],
    secondary_muscles: ['deltoïdes', 'fessiers', 'triceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Tabata 8 Rounds KB Swings',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Tabata 8 Rounds 20sec KB Swings 53lbs 10sec rest posterior chain',
    primary_muscles: ['fessiers', 'ischio-jambiers'],
    secondary_muscles: ['érecteurs', 'deltoïdes', 'abdominaux'],
    equipment: ['kettlebell'],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Tabata 8 Rounds Box Jumps',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Tabata 8 Rounds 20sec Box Jumps 20in 10sec rest explosive power',
    primary_muscles: ['quadriceps', 'fessiers', 'mollets'],
    secondary_muscles: ['ischio-jambiers', 'abdominaux'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'RFT 4 Rounds Power Clean + Jerk',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Rounds For Time 4 Rounds 9 Power Cleans 135lbs 6 Push Jerks',
    primary_muscles: ['quadriceps', 'deltoïdes', 'trapèzes'],
    secondary_muscles: ['fessiers', 'érecteurs', 'triceps'],
    equipment: ['barbell'],
    sets_min: 4,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'RFT 5 Rounds Pull-ups + Push-ups + Squats',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Rounds For Time 5 Rounds 10 Pull-ups 15 Push-ups 20 Squats',
    primary_muscles: ['dorsaux', 'pectoraux', 'quadriceps'],
    secondary_muscles: ['biceps', 'triceps', 'fessiers'],
    equipment: ['pull-up bar'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'RFT 3 Rounds Deadlifts + Box Jumps + Pull-ups',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Rounds For Time 3 Rounds 15 Deadlifts 225lbs 20 Box Jumps 25 Pull-ups',
    primary_muscles: ['érecteurs', 'quadriceps', 'dorsaux'],
    secondary_muscles: ['fessiers', 'mollets', 'biceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Ladder 1-10 Thrusters + Pull-ups',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Ascending Ladder 1-10 Thrusters 95lbs Pull-ups volume accumulation',
    primary_muscles: ['quadriceps', 'deltoïdes', 'dorsaux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Ladder 10-1 Burpees + KB Swings',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Descending Ladder 10-1 Burpees KB Swings 53lbs decreasing reps',
    primary_muscles: ['pectoraux', 'fessiers'],
    secondary_muscles: ['quadriceps', 'ischio-jambiers', 'deltoïdes'],
    equipment: ['kettlebell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Death By 10m Shuttle Sprints',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Death By 10m Shuttle Sprints Min1=1 Min2=2 until failure cardio',
    primary_muscles: ['quadriceps', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Death By Burpees',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Death By Burpees Min1=1 Min2=2 until failure metabolic conditioning',
    primary_muscles: ['pectoraux', 'quadriceps', 'mollets'],
    secondary_muscles: ['deltoïdes', 'fessiers', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Chipper 10-to-1 Mixed Movements',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Chipper 10-to-1 10 movements descending reps each endurance test',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps', 'abdominaux'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Partner WOD Alternating Rounds',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Partner WOD Alternating Rounds 10 Rounds partner1 works partner2 rests',
    primary_muscles: ['quadriceps', 'pectoraux', 'dorsaux'],
    secondary_muscles: ['fessiers', 'triceps', 'biceps'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Partner WOD Synchronized Work',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Partner WOD Synchronized Work both work simultaneously teamwork',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Buy-In 1 Mile Run + AMRAP',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Buy-In 1 Mile Run then AMRAP 10min Burpees + Thrusters conditioning',
    primary_muscles: ['quadriceps', 'mollets', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'triceps'],
    equipment: ['barbell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Cash-Out 100 Burpees Finisher',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Cash-Out 100 Burpees Finisher after main WOD metabolic finisher',
    primary_muscles: ['pectoraux', 'quadriceps', 'mollets'],
    secondary_muscles: ['deltoïdes', 'fessiers', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 100,
    reps_max: 100,
    rest_sec: 0,
  },
  {
    name: 'Interval 30-20-10 Work Rest Ratio',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'Interval Training 30sec work 20sec rest 10 rounds variable movements',
    primary_muscles: ['quadriceps', 'pectoraux', 'dorsaux'],
    secondary_muscles: ['fessiers', 'triceps', 'biceps'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'AMRAP 25min Long Endurance WOD',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'AMRAP 25min Long Endurance WOD 400m Run 30 Squats 20 Push-ups stamina',
    primary_muscles: ['quadriceps', 'mollets', 'pectoraux'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'EMOM 24min Multi-Modal',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'EMOM 24min Min1 Row Min2 Lift Min3 Gymnastics Min4 Rest cycle repeat',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps', 'abdominaux'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 6,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'For Time 7 Rounds of 7 Reps Lucky 7',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'For Time 7 Rounds of 7 Reps 7 movements per round lucky number',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: [],
    sets_min: 7,
    sets_max: 7,
    reps_min: 7,
    reps_max: 7,
    rest_sec: 0,
  },
  {
    name: 'AMRAP Couplet 15min 2 Movements',
    category: 'metcon_format',
    difficulty: 'intermediate',
    description: 'AMRAP Couplet 15min 2 Movements alternating simple pairing',
    primary_muscles: ['quadriceps', 'dorsaux'],
    secondary_muscles: ['fessiers', 'biceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'AMRAP Triplet 12min 3 Movements',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'AMRAP Triplet 12min 3 Movements classic format three exercise rotation',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Fight Gone Bad Format 5 Stations',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'Fight Gone Bad 5 Stations 1min each 1min rest 3 rounds benchmark format',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps', 'abdominaux'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'DT Format 5 Rounds Heavy Complex',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: 'DT Format 5 Rounds Heavy Complex Deadlifts Hang Cleans Push Jerks technical',
    primary_muscles: ['érecteurs', 'quadriceps', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'trapèzes', 'triceps'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: '21-18-15-12-9-6-3 Long Descending Ladder',
    category: 'metcon_format',
    difficulty: 'advanced',
    description: '21-18-15-12-9-6-3 Long Descending Ladder 7 rounds decreasing volume',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
];

async function main() {
  console.log('🔥 Seeding Functional MetCon Formats (42 exercises)...\n');

  let success = 0;
  let failed = 0;

  for (const ex of metconFormats) {
    try {
      await seedExercise(ex);
      success++;
    } catch (error) {
      console.error(`❌ Failed to seed ${ex.name}:`, error);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success}/${metconFormats.length}`);
  console.log(`❌ Failed: ${failed}/${metconFormats.length}`);
  console.log('\n🎯 MetCon Formats enrichment complete!');
}

main().then(() => process.exit(0));
