import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const muscleCache = new Map<string, string>();
const equipmentCache = new Map<string, string>();

async function getMuscleId(name: string): Promise<string | null> {
  if (muscleCache.has(name)) return muscleCache.get(name)!;
  const { data } = await supabase.from('muscle_groups').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) muscleCache.set(name, data.id);
  return data?.id || null;
}

async function getEquipmentId(name: string): Promise<string | null> {
  if (equipmentCache.has(name)) return equipmentCache.get(name)!;
  const { data } = await supabase.from('equipment_types').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) equipmentCache.set(name, data.id);
  return data?.id || null;
}

async function seedExercise(ex: any) {
  const primaryMuscleIds = (await Promise.all((ex.primary_muscles || []).map(getMuscleId))).filter(Boolean);
  const secondaryMuscleIds = (await Promise.all((ex.secondary_muscles || []).map(getMuscleId))).filter(Boolean);
  const equipmentIds = (await Promise.all((ex.equipment || []).map(getEquipmentId))).filter(Boolean);

  const { data: exercise, error } = await supabase.from('exercises').insert({
    name: ex.name,
    discipline: 'endurance',
    category: ex.category,
    difficulty: ex.difficulty,
    description_short: ex.description,
    movement_pattern: ex.movement_pattern || 'cardio',
    is_validated: true,
    typical_sets_min: ex.sets_min || 1,
    typical_sets_max: ex.sets_max || 1,
    typical_reps_min: ex.reps_min || 1,
    typical_reps_max: ex.reps_max || 1,
    typical_rest_sec: ex.rest_sec || 60,
  }).select().single();

  if (error) {
    console.error(`Error inserting ${ex.name}:`, error.message);
    return;
  }

  if (!exercise) return;

  if (primaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      primaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'primary' }))
    );
  }

  if (secondaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      secondaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'secondary' }))
    );
  }

  if (equipmentIds.length > 0) {
    await supabase.from('exercise_equipment').insert(
      equipmentIds.map(id => ({ exercise_id: exercise.id, equipment_type_id: id, is_required: true }))
    );
  }

  console.log(`✅ ${ex.name}`);
}

const swimmingExercises = [
  {
    name: 'Catch-Up Drill Freestyle',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill catch-up crawl technique coordination bras',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['triceps', 'abdominaux'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Fingertip Drag Drill',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill fingertip drag technique récupération haute coude',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['trapèzes'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Kickboard Kick Drill',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Battements planche kick drill jambes isolation',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Pull Buoy Drill Arms Only',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill pull buoy bras seuls technique traction',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['triceps', 'biceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Bilateral Breathing Drill',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill respiration bilatérale 3-5-7 temps équilibre',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Sculling Drill Figure 8',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill sculling figure 8 appui eau sensation',
    primary_muscles: ['avant-bras', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Single Arm Drill Freestyle',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill un bras crawl isolation technique correction',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['triceps'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Fist Drill Closed Hand',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill poing fermé avant-bras sensation appui',
    primary_muscles: ['dorsaux', 'avant-bras'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Side Kick Drill',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill battements côté rotation équilibre',
    primary_muscles: ['quadriceps', 'obliques'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: '6-3-6 Drill Rotation',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill 6-3-6 rotation corps équilibre technique',
    primary_muscles: ['dorsaux', 'obliques'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'CSS Test Critical Swim Speed',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Test CSS vitesse critique natation 400m+200m',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 600,
  },
  {
    name: 'CSS Intervals 100m Repeats',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Intervalles CSS 100m allure critique 15sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 10,
    sets_max: 16,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 15,
  },
  {
    name: 'CSS Intervals 200m Repeats',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Intervalles CSS 200m allure critique 30sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'CSS Intervals 400m Repeats',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Intervalles CSS 400m allure critique 60sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Threshold Set 1000m Continuous',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Série seuil 1000m continu allure T-pace',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Threshold Set 5x200m',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Série seuil 5x200m T-pace 20-30sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 25,
  },
  {
    name: 'Threshold Set 10x100m',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Série seuil 10x100m T-pace 10-15sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 12,
  },
  {
    name: 'VO2max Set 8x50m Fast',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Série VO2max 8x50m rapide 30sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'VO2max Set 6x75m Fast',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Série VO2max 6x75m rapide 45sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 45,
  },
  {
    name: 'Sprint Set 10x25m Maximum',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Sprints 10x25m effort maximal 30sec repos',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['triceps', 'quadriceps'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Descending Set 400-300-200-100',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Série descendante 400-300-200-100 allure croissante',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Pyramid Set 100-200-300-200-100',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Pyramide 100-200-300-200-100 allure constante',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 45,
  },
  {
    name: 'Broken 1000m 10x100m',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Broken 1000m 10x100m 5sec repos allure 1000m',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 5,
  },
  {
    name: 'Negative Split 500m',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Negative split 500m 2ème moitié plus rapide',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Long Endurance Swim 2000m',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Nage endurance longue 2000m Z2 aérobie',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Easy Recovery Swim 1000m',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Nage récupération facile 1000m Z1 technique',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'IMX Individual Medley',
    category: 'swimming',
    difficulty: 'advanced',
    description: '4 nages individuel medley papillon-dos-brasse-crawl',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['pectoraux', 'abdominaux', 'quadriceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Backstroke Technique Drill',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill technique dos crawlé rotation corps',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['trapèzes'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Breaststroke Technique Drill',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill technique brasse synchronisation bras-jambes',
    primary_muscles: ['pectoraux', 'adducteurs'],
    secondary_muscles: ['deltoïdes', 'quadriceps'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Butterfly Technique Drill',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Drill technique papillon ondulation coordination',
    primary_muscles: ['dorsaux', 'pectoraux'],
    secondary_muscles: ['abdominaux', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 45,
  },
  {
    name: 'Underwater Kick Drill',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill battements sous eau apnée puissance',
    primary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Streamline Push-Off Drill',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Drill streamline poussée mur position hydrodynamique',
    primary_muscles: ['abdominaux', 'dorsaux'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Hypoxic Training 3-5-7',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Entraînement hypoxique 3-5-7 respirations tolérance CO2',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['abdominaux'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 45,
  },
  {
    name: 'Timed Distance 1500m T-Pace',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Distance chronométrée 1500m allure objectif',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Open Water Simulation',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Simulation eau libre sighting navigation sans ligne',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Draft Practice Swimming',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Pratique drafting aspiration natation groupe',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Tarzan Drill Head Up',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill Tarzan tête haute water polo sighting',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['trapèzes', 'abdominaux'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Vertical Kicking Treading',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Battements verticaux sur place treading water',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['abdominaux', 'mollets'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Paddle Work Power',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'Travail plaquettes puissance traction résistance',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['triceps', 'pectoraux'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Snorkel Drill No Breathing',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Drill tuba technique sans respiration distraction',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Tempo Trainer Pace Work',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Travail tempo trainer cadence régularité allure',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Finish Strong Last 25m',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Finish fort 25m finaux sprint simulation course',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 45,
  },
  {
    name: 'Distance Per Stroke DPS',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Distance par mouvement efficacité glisse technique',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Build Swim Progressive',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Nage progressive build allure croissante 25-50-75-100',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Golf Swim Strokes Count',
    category: 'swimming',
    difficulty: 'beginner',
    description: 'Golf natation compter mouvements efficacité technique',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'USRPT Ultra Short Race Pace',
    category: 'swimming',
    difficulty: 'advanced',
    description: 'USRPT ultra short allure course répétitions courtes',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 20,
    sets_max: 30,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Pull-Kick-Swim Transition',
    category: 'swimming',
    difficulty: 'intermediate',
    description: 'Transition pull-kick-swim coordination complète',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'triceps'],
    equipment: [],
    sets_min: 3,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
];

async function main() {
  console.log('🏊 Seeding Endurance Swimming Drills & Intervals (50 exercises)...\n');

  let success = 0;
  let failed = 0;

  for (const ex of swimmingExercises) {
    try {
      await seedExercise(ex);
      success++;
    } catch (error) {
      console.error(`❌ Failed to seed ${ex.name}:`, error);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success}/${swimmingExercises.length}`);
  console.log(`❌ Failed: ${failed}/${swimmingExercises.length}`);
  console.log('\n🎯 Swimming drills & intervals enrichment complete!');
}

main().then(() => process.exit(0));
