import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const muscleCache = new Map<string, string>();
const equipmentCache = new Map<string, string>();

async function getMuscleId(name: string): Promise<string | null> {
  if (muscleCache.has(name)) return muscleCache.get(name)!;
  const { data } = await supabase.from('muscle_groups').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) muscleCache.set(name, data.id);
  return data?.id || null;
}

async function getEquipmentId(name: string): Promise<string | null> {
  if (equipmentCache.has(name)) return equipmentCache.get(name)!;
  const { data } = await supabase.from('equipment_types').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) equipmentCache.set(name, data.id);
  return data?.id || null;
}

async function seedExercise(ex: any) {
  const primaryMuscleIds = (await Promise.all((ex.primary_muscles || []).map(getMuscleId))).filter(Boolean);
  const secondaryMuscleIds = (await Promise.all((ex.secondary_muscles || []).map(getMuscleId))).filter(Boolean);
  const equipmentIds = (await Promise.all((ex.equipment || []).map(getEquipmentId))).filter(Boolean);

  const { data: exercise, error } = await supabase.from('exercises').insert({
    name: ex.name,
    discipline: 'endurance',
    category: ex.category,
    difficulty: ex.difficulty,
    description_short: ex.description,
    movement_pattern: ex.movement_pattern || 'cardio',
    is_validated: true,
    typical_sets_min: ex.sets_min || 1,
    typical_sets_max: ex.sets_max || 1,
    typical_reps_min: ex.reps_min || 1,
    typical_reps_max: ex.reps_max || 1,
    typical_rest_sec: ex.rest_sec || 60,
  }).select().single();

  if (error) {
    console.error(`Error inserting ${ex.name}:`, error.message);
    return;
  }

  if (!exercise) return;

  if (primaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      primaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'primary' }))
    );
  }

  if (secondaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      secondaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'secondary' }))
    );
  }

  if (equipmentIds.length > 0) {
    await supabase.from('exercise_equipment').insert(
      equipmentIds.map(id => ({ exercise_id: exercise.id, equipment_type_id: id, is_required: true }))
    );
  }

  console.log(`✅ ${ex.name}`);
}

const enduranceExercises = [
  {
    name: 'Brick Bike-to-Run Olympic',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Brique vélo-course transition olympique 40K bike 10K run',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Brick Bike-to-Run Sprint',
    category: 'triathlon',
    difficulty: 'intermediate',
    description: 'Brique vélo-course transition sprint 20K bike 5K run',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Brick Bike-to-Run Half Ironman',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Brique vélo-course half ironman 90K bike 21K run',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'fessiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Brick Swim-to-Bike Transition',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Brique natation-vélo transition T1 practice',
    primary_muscles: ['dorsaux', 'quadriceps', 'ischio-jambiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Triple Brick Swim-Bike-Run',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Triple brique 3 disciplines enchaînées simulation course',
    primary_muscles: ['dorsaux', 'quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'T1 Transition Practice',
    category: 'triathlon',
    difficulty: 'intermediate',
    description: 'Pratique T1 natation vers vélo vitesse efficacité',
    primary_muscles: ['dorsaux', 'quadriceps'],
    equipment: [],
    sets_min: 5,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'T2 Transition Practice',
    category: 'triathlon',
    difficulty: 'intermediate',
    description: 'Pratique T2 vélo vers course vitesse technique',
    primary_muscles: ['quadriceps', 'mollets'],
    equipment: [],
    sets_min: 5,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Sprint Triathlon Simulation',
    category: 'triathlon',
    difficulty: 'intermediate',
    description: 'Simulation triathlon sprint 750m swim 20K bike 5K run',
    primary_muscles: ['dorsaux', 'quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Olympic Triathlon Simulation',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Simulation triathlon olympique 1500m swim 40K bike 10K run',
    primary_muscles: ['dorsaux', 'quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Open Water Swim Practice',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Natation eau libre sighting navigation combinaison',
    primary_muscles: ['dorsaux', 'deltoïdes'],
    secondary_muscles: ['quadriceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Aquathlon Swim-Run',
    category: 'triathlon',
    difficulty: 'intermediate',
    description: 'Aquathlon natation-course enchaînement sans vélo',
    primary_muscles: ['dorsaux', 'quadriceps', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Duathlon Run-Bike-Run',
    category: 'triathlon',
    difficulty: 'intermediate',
    description: 'Duathlon course-vélo-course enchaînement sans natation',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Ironman 70.3 Simulation',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Simulation Half Ironman 1.9K swim 90K bike 21K run',
    primary_muscles: ['dorsaux', 'quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Beach Run Soft Sand',
    category: 'triathlon',
    difficulty: 'advanced',
    description: 'Course plage sable mou résistance puissance jambes',
    primary_muscles: ['quadriceps', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Rowing Machine 2K Test',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Test rameur 2000m effort maximal benchmark',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Rowing 500m Intervals',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Intervalles rameur 500m max effort 2min repos',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Rowing 1000m Intervals',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Intervalles rameur 1000m threshold 3min repos',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps', 'abdominaux'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Rowing Pyramid 250-500-750-500-250',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Pyramide rameur 250-500-750-500-250m intensité croissante',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Rowing 10K Long Distance',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Distance longue rameur 10000m endurance Z2',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Rowing 30min Steady State',
    category: 'rowing',
    difficulty: 'intermediate',
    description: 'Rameur 30min allure constante Z2-Z3 base aérobie',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Rowing Sprints 100m Max',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Sprints rameur 100m max power 3min récupération',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Rowing Stroke Rate Drills',
    category: 'rowing',
    difficulty: 'intermediate',
    description: 'Drills rameur cadence 18-20-22-24-26 SPM technique',
    primary_muscles: ['dorsaux', 'quadriceps'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Rowing Power 10s',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Power 10s rameur 10 coups max puissance répétitions',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 90,
  },
  {
    name: 'Rowing Tabata 20-10',
    category: 'rowing',
    difficulty: 'advanced',
    description: 'Tabata rameur 20sec max 10sec repos 8 rounds',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Rowing Pete Plan Beginner',
    category: 'rowing',
    difficulty: 'beginner',
    description: 'Pete Plan débutant rameur programme structuré',
    primary_muscles: ['dorsaux', 'quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Rowing Recovery 20min Z1',
    category: 'rowing',
    difficulty: 'beginner',
    description: 'Récupération rameur 20min Z1 facile technique',
    primary_muscles: ['dorsaux', 'quadriceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Assault Bike 10 Calories Sprint',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Sprint assault bike 10 calories max effort',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes', 'triceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Assault Bike 20 Calories Repeats',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Répétitions assault bike 20 calories Z4-Z5',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Assault Bike Tabata 20-10',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Tabata assault bike 20sec max 10sec repos brutal',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes', 'triceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Assault Bike 30min Steady State',
    category: 'assault_bike',
    difficulty: 'intermediate',
    description: 'Assault bike 30min allure constante Z2-Z3',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Assault Bike EMOM 10 Cal',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'EMOM assault bike 10 cal chaque minute 10-15min',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 10,
    sets_max: 15,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Assault Bike Pyramid Calories',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Pyramide assault bike 5-10-15-20-15-10-5 calories',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Assault Bike Recovery 15min',
    category: 'assault_bike',
    difficulty: 'beginner',
    description: 'Récupération assault bike 15min Z1 facile',
    primary_muscles: ['quadriceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Assault Bike 100 Calories Challenge',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Challenge assault bike 100 calories temps record',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Assault Bike Death By Calories',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Death by calories 1 cal min1 2 cal min2 progression',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Assault Bike Intervals 40-20',
    category: 'assault_bike',
    difficulty: 'advanced',
    description: 'Intervalles 40sec on 20sec off 12-16 rounds',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 12,
    sets_max: 16,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 20,
  },
  {
    name: 'Ski Erg 1000m Intervals',
    category: 'skiing',
    difficulty: 'advanced',
    description: 'Intervalles ski erg 1000m Z4 3min repos',
    primary_muscles: ['dorsaux', 'abdominaux'],
    secondary_muscles: ['deltoïdes', 'triceps', 'quadriceps'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Ski Erg 500m Sprints',
    category: 'skiing',
    difficulty: 'advanced',
    description: 'Sprints ski erg 500m max effort 2min repos',
    primary_muscles: ['dorsaux', 'abdominaux'],
    secondary_muscles: ['deltoïdes', 'triceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Ski Erg 30min Steady State',
    category: 'skiing',
    difficulty: 'intermediate',
    description: 'Ski erg 30min allure constante Z2-Z3',
    primary_muscles: ['dorsaux', 'abdominaux'],
    secondary_muscles: ['deltoïdes', 'triceps', 'quadriceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Ski Erg Tabata 20-10',
    category: 'skiing',
    difficulty: 'advanced',
    description: 'Tabata ski erg 20sec max 10sec repos 8 rounds',
    primary_muscles: ['dorsaux', 'abdominaux'],
    secondary_muscles: ['deltoïdes', 'triceps'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: 'Elliptical 30min Z2 Aerobic',
    category: 'elliptical',
    difficulty: 'beginner',
    description: 'Elliptique 30min Z2 aérobie base endurance',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Elliptical Intervals HIIT',
    category: 'elliptical',
    difficulty: 'intermediate',
    description: 'Intervalles HIIT elliptique 2min on 1min off',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'deltoïdes'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Stair Climber 20min Steady',
    category: 'stair_climber',
    difficulty: 'intermediate',
    description: 'Escaliers 20min allure constante Z3',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['mollets', 'ischio-jambiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Stair Climber Intervals Fast',
    category: 'stair_climber',
    difficulty: 'advanced',
    description: 'Intervalles escaliers rapides 3min on 2min off',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['mollets', 'ischio-jambiers'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Jump Rope 10min Continuous',
    category: 'jump_rope',
    difficulty: 'intermediate',
    description: 'Corde à sauter 10min continu coordination cardio',
    primary_muscles: ['mollets', 'quadriceps'],
    secondary_muscles: ['deltoïdes', 'avant-bras'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Jump Rope Double Unders',
    category: 'jump_rope',
    difficulty: 'advanced',
    description: 'Double unders corde à sauter 50-100 reps',
    primary_muscles: ['mollets', 'quadriceps'],
    secondary_muscles: ['deltoïdes', 'avant-bras'],
    equipment: [],
    sets_min: 5,
    sets_max: 10,
    reps_min: 50,
    reps_max: 100,
    rest_sec: 60,
  },
  {
    name: 'Battle Ropes 30sec Waves',
    category: 'battle_ropes',
    difficulty: 'intermediate',
    description: 'Cordes ondulatoires 30sec waves max effort',
    primary_muscles: ['deltoïdes', 'dorsaux'],
    secondary_muscles: ['abdominaux', 'avant-bras'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Battle Ropes Slams',
    category: 'battle_ropes',
    difficulty: 'intermediate',
    description: 'Cordes slams explosifs 20sec max puissance',
    primary_muscles: ['deltoïdes', 'dorsaux'],
    secondary_muscles: ['abdominaux', 'triceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Sled Push Heavy 20m',
    category: 'sled',
    difficulty: 'advanced',
    description: 'Poussée traîneau lourd 20m puissance jambes',
    primary_muscles: ['quadriceps', 'fessiers'],
    secondary_muscles: ['ischio-jambiers', 'mollets', 'abdominaux'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Sled Pull 30m',
    category: 'sled',
    difficulty: 'advanced',
    description: 'Traction traîneau 30m dorsaux force traction',
    primary_muscles: ['dorsaux', 'ischio-jambiers'],
    secondary_muscles: ['fessiers', 'trapèzes', 'biceps'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
];

async function main() {
  console.log('🏊‍♂️🚴‍♂️🏃 Seeding Endurance Triathlon, Rowing & Other (50 exercises)...\n');

  let success = 0;
  let failed = 0;

  for (const ex of enduranceExercises) {
    try {
      await seedExercise(ex);
      success++;
    } catch (error) {
      console.error(`❌ Failed to seed ${ex.name}:`, error);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success}/${enduranceExercises.length}`);
  console.log(`❌ Failed: ${failed}/${enduranceExercises.length}`);
  console.log('\n🎯 Triathlon, Rowing & Other endurance enrichment complete!');
}

main().then(() => process.exit(0));
