import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const muscleCache = new Map<string, string>();
const equipmentCache = new Map<string, string>();

async function getMuscleId(name: string): Promise<string | null> {
  if (muscleCache.has(name)) return muscleCache.get(name)!;
  const { data } = await supabase.from('muscle_groups').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) muscleCache.set(name, data.id);
  return data?.id || null;
}

async function getEquipmentId(name: string): Promise<string | null> {
  if (equipmentCache.has(name)) return equipmentCache.get(name)!;
  const { data } = await supabase.from('equipment_types').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) equipmentCache.set(name, data.id);
  return data?.id || null;
}

async function seedExercise(ex: any) {
  const primaryMuscleIds = (await Promise.all((ex.primary_muscles || []).map(getMuscleId))).filter(Boolean);
  const secondaryMuscleIds = (await Promise.all((ex.secondary_muscles || []).map(getMuscleId))).filter(Boolean);
  const equipmentIds = (await Promise.all((ex.equipment || []).map(getEquipmentId))).filter(Boolean);

  const { data: exercise, error } = await supabase.from('exercises').insert({
    name: ex.name,
    discipline: 'functional',
    category: ex.category,
    difficulty: ex.difficulty,
    description_short: ex.description,
    movement_pattern: ex.movement_pattern || 'compound',
    is_validated: true,
    typical_sets_min: ex.sets_min || 1,
    typical_sets_max: ex.sets_max || 1,
    typical_reps_min: ex.reps_min || 1,
    typical_reps_max: ex.reps_max || 1,
    typical_rest_sec: ex.rest_sec || 0,
  }).select().single();

  if (error) {
    console.error(`Error inserting ${ex.name}:`, error.message);
    return;
  }

  if (!exercise) return;

  if (primaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      primaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'primary' }))
    );
  }

  if (secondaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      secondaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'secondary' }))
    );
  }

  if (equipmentIds.length > 0) {
    await supabase.from('exercise_equipment').insert(
      equipmentIds.map(id => ({ exercise_id: exercise.id, equipment_type_id: id, is_required: true }))
    );
  }

  console.log(`✅ ${ex.name}`);
}

const wodCombinations = [
  {
    name: 'Couplet Deadlifts + Box Jumps',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Couplet 5 Rounds 15 Deadlifts 225lbs 20 Box Jumps 24in power+plyo',
    primary_muscles: ['érecteurs', 'quadriceps'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'mollets'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Couplet Thrusters + Pull-ups Classic',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Couplet 21-15-9 Thrusters 95lbs Pull-ups Fran-style pairing',
    primary_muscles: ['quadriceps', 'deltoïdes', 'dorsaux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Couplet Row + Burpees Cardio Power',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Couplet 4 Rounds 500m Row 20 Burpees cardio metabolic',
    primary_muscles: ['dorsaux', 'pectoraux', 'quadriceps'],
    secondary_muscles: ['biceps', 'triceps', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Couplet KB Swings + Goblet Squats',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Couplet AMRAP 15min 15 KB Swings 53lbs 12 Goblet Squats posterior+anterior',
    primary_muscles: ['fessiers', 'quadriceps'],
    secondary_muscles: ['ischio-jambiers', 'érecteurs', 'deltoïdes'],
    equipment: ['kettlebell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Couplet Wall Balls + Double-Unders',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Couplet For Time 100 Wall Balls 20lbs 100 Double-Unders skill+cardio',
    primary_muscles: ['quadriceps', 'deltoïdes', 'mollets'],
    secondary_muscles: ['fessiers', 'triceps', 'abdominaux'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 100,
    reps_max: 100,
    rest_sec: 0,
  },
  {
    name: 'Triplet Run + Squats + Pull-ups',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Triplet 5 Rounds 400m Run 30 Squats 20 Pull-ups total body conditioning',
    primary_muscles: ['quadriceps', 'mollets', 'dorsaux'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'biceps'],
    equipment: ['pull-up bar'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Triplet Power Cleans + Push-ups + Box Jumps',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Triplet 3 Rounds 15 Power Cleans 135lbs 20 Push-ups 25 Box Jumps',
    primary_muscles: ['quadriceps', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'triceps', 'mollets'],
    equipment: ['barbell'],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Triplet Deadlifts + Handstand Push-ups + KB Swings',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Triplet 21-15-9 Deadlifts 225lbs HSPU KB Swings 70lbs three pillars',
    primary_muscles: ['érecteurs', 'deltoïdes', 'fessiers'],
    secondary_muscles: ['fessiers', 'triceps', 'ischio-jambiers'],
    equipment: ['barbell', 'kettlebell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Triplet Burpees + Sit-ups + Air Squats',
    category: 'wod_combination',
    difficulty: 'beginner',
    description: 'Triplet AMRAP 20min 10 Burpees 15 Sit-ups 20 Air Squats bodyweight',
    primary_muscles: ['pectoraux', 'abdominaux', 'quadriceps'],
    secondary_muscles: ['deltoïdes', 'fléchisseurs hanches', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Triplet Thrusters + Chest-to-Bar + Burpees Over Bar',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Triplet 5 Rounds 10 Thrusters 95lbs 15 C2B 20 Burpees Over Bar high volume',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps', 'mollets'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Chipper 10 Movements Descending',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Chipper For Time 10 movements 50-40-30-20-10 reps each descending ladder',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps', 'abdominaux'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Chipper 7 Movements Equal Reps',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Chipper For Time 7 movements 21 reps each straight through endurance',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 21,
    reps_max: 21,
    rest_sec: 0,
  },
  {
    name: 'Chipper 5 Movements High Volume',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Chipper For Time 5 movements 100-75-50-25-10 reps volume test',
    primary_muscles: ['quadriceps', 'dorsaux', 'mollets'],
    secondary_muscles: ['fessiers', 'biceps', 'ischio-jambiers'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Complex Clean + Front Squat + Jerk',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Complex 5x3 Clean Front Squat Push Jerk no drop barbell technique',
    primary_muscles: ['quadriceps', 'deltoïdes', 'trapèzes'],
    secondary_muscles: ['fessiers', 'érecteurs', 'triceps'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 3,
    reps_max: 3,
    rest_sec: 120,
  },
  {
    name: 'Complex Snatch + Overhead Squat + Snatch Balance',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Complex 5x2 Snatch OHS Snatch Balance olympic technical mastery',
    primary_muscles: ['quadriceps', 'deltoïdes', 'fessiers'],
    secondary_muscles: ['érecteurs', 'trapèzes', 'dorsaux'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 2,
    reps_max: 2,
    rest_sec: 120,
  },
  {
    name: 'Complex Deadlift + Hang Clean + Front Squat + Push Press',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Complex EMOM 10min full body barbell sequence 4 movements continuous',
    primary_muscles: ['érecteurs', 'quadriceps', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'trapèzes', 'triceps'],
    equipment: ['barbell'],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Mixed Modal Run + Lift + Gymnastics',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Mixed Modal 3 Rounds 800m Run 21 Thrusters 95lbs 12 Pull-ups three domains',
    primary_muscles: ['quadriceps', 'mollets', 'deltoïdes', 'dorsaux'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 3,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Mixed Modal Row + KB + Bodyweight',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Mixed Modal 4 Rounds 500m Row 21 KB Swings 53lbs 15 Burpees cardio+power',
    primary_muscles: ['dorsaux', 'fessiers', 'pectoraux'],
    secondary_muscles: ['biceps', 'ischio-jambiers', 'deltoïdes'],
    equipment: ['kettlebell'],
    sets_min: 4,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Mixed Modal Assault Bike + Deadlifts + Box Jumps',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Mixed Modal 5 Rounds 15 Cal Assault Bike 12 Deadlifts 225lbs 9 Box Jumps',
    primary_muscles: ['quadriceps', 'érecteurs', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'deltoïdes'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Hero Style Long Endurance WOD',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Hero Style 1 Mile Run 100 Pull-ups 200 Push-ups 300 Squats 1 Mile Run tribute',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux', 'mollets'],
    secondary_muscles: ['biceps', 'triceps', 'fessiers', 'ischio-jambiers'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Pyramid Ascending 1-2-3-4-5 Movements',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Pyramid Ascending 1-2-3-4-5 multiple movements increasing reps',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Pyramid Descending 10-8-6-4-2 Heavy Load',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Pyramid Descending 10-8-6-4-2 heavy lifts decreasing reps strength focus',
    primary_muscles: ['érecteurs', 'quadriceps', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'trapèzes', 'triceps'],
    equipment: ['barbell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Pyramid Up-Down 1-2-3-2-1 Time Cap',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Pyramid Up-Down 1-2-3-2-1 ascending then descending symmetrical',
    primary_muscles: ['quadriceps', 'dorsaux'],
    secondary_muscles: ['fessiers', 'biceps'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Team WOD 3 Person Rotation',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Team WOD 3 Person Rotation one works two rest continuous movement',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Team WOD Partner Chipper',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Team WOD Partner Chipper divide reps strategically team strategy',
    primary_muscles: ['quadriceps', 'dorsaux', 'pectoraux'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'EMOMx3 Tri-Modal Rotation',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'EMOMx3 Tri-Modal Rotation Min1 Cardio Min2 Lift Min3 Gymnastics 5 cycles',
    primary_muscles: ['quadriceps', 'dorsaux', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'biceps', 'triceps'],
    equipment: ['barbell', 'pull-up bar'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Buy-In Strength + AMRAP Conditioning',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Buy-In Strength work then AMRAP Conditioning two phase workout',
    primary_muscles: ['quadriceps', 'érecteurs', 'pectoraux'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'triceps'],
    equipment: ['barbell'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Cash-Out AMRAP + Burnout Finisher',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Cash-Out AMRAP main work then Burnout Finisher max effort ending',
    primary_muscles: ['quadriceps', 'dorsaux', 'mollets'],
    secondary_muscles: ['fessiers', 'biceps', 'ischio-jambiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Interval Sprints + Strength Alternating',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Interval Sprints + Strength Alternating 10 Rounds cardio lift rotation',
    primary_muscles: ['quadriceps', 'mollets', 'érecteurs'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'trapèzes'],
    equipment: ['barbell'],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Front Squat + Back Squat + Overhead Squat Tri-Squat',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Tri-Squat Complex Front Back Overhead Squat 5x3 each position mastery',
    primary_muscles: ['quadriceps', 'deltoïdes'],
    secondary_muscles: ['fessiers', 'érecteurs', 'trapèzes'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 9,
    reps_max: 9,
    rest_sec: 120,
  },
  {
    name: 'Pull + Push + Squat Full Body Couplet',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Pull Push Squat Couplet AMRAP 15min full body movement patterns',
    primary_muscles: ['dorsaux', 'pectoraux', 'quadriceps'],
    secondary_muscles: ['biceps', 'triceps', 'fessiers'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Olympic Lift + Monostructural Cardio',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Olympic Lift + Monostructural Cardio 5 Rounds technical lift pure cardio',
    primary_muscles: ['quadriceps', 'deltoïdes', 'mollets'],
    secondary_muscles: ['fessiers', 'trapèzes', 'ischio-jambiers'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Gymnastics Benchmark + Cardio Finish',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Gymnastics Benchmark + Cardio Finish skill work metabolic conditioning',
    primary_muscles: ['dorsaux', 'pectoraux', 'quadriceps', 'mollets'],
    secondary_muscles: ['biceps', 'triceps', 'fessiers', 'abdominaux'],
    equipment: ['pull-up bar'],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Heavy Day 5-5-5-5-5 Strength Build',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Heavy Day 5x5 Strength Build progressive load max effort sets',
    primary_muscles: ['érecteurs', 'quadriceps'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'trapèzes'],
    equipment: ['barbell'],
    sets_min: 5,
    sets_max: 5,
    reps_min: 5,
    reps_max: 5,
    rest_sec: 180,
  },
  {
    name: 'Volume Day 3x10 Hypertrophy Focus',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Volume Day 3x10 Hypertrophy Focus controlled tempo muscle building',
    primary_muscles: ['pectoraux', 'quadriceps', 'dorsaux'],
    secondary_muscles: ['triceps', 'fessiers', 'biceps'],
    equipment: ['barbell'],
    sets_min: 3,
    sets_max: 3,
    reps_min: 10,
    reps_max: 10,
    rest_sec: 90,
  },
  {
    name: 'Power Day Explosive Olympic Lifts',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Power Day Explosive Olympic Lifts 8x2 speed strength maximal power',
    primary_muscles: ['quadriceps', 'deltoïdes', 'trapèzes'],
    secondary_muscles: ['fessiers', 'érecteurs', 'triceps'],
    equipment: ['barbell'],
    sets_min: 8,
    sets_max: 8,
    reps_min: 2,
    reps_max: 2,
    rest_sec: 150,
  },
  {
    name: 'Conditioning Day Long AMRAP 30min',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Conditioning Day Long AMRAP 30min sustained effort aerobic capacity',
    primary_muscles: ['quadriceps', 'dorsaux', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers', 'biceps'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Recovery Day Light Technical Work',
    category: 'wod_combination',
    difficulty: 'beginner',
    description: 'Recovery Day Light Technical Work EMOM 20min skill practice low intensity',
    primary_muscles: ['quadriceps', 'deltoïdes'],
    secondary_muscles: ['dorsaux', 'abdominaux'],
    equipment: ['barbell'],
    sets_min: 20,
    sets_max: 20,
    reps_min: 3,
    reps_max: 5,
    rest_sec: 0,
  },
  {
    name: 'Sprint Day Short Intense Intervals',
    category: 'wod_combination',
    difficulty: 'advanced',
    description: 'Sprint Day Short Intense Intervals 10x100m maximal effort alactic power',
    primary_muscles: ['quadriceps', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers'],
    equipment: [],
    sets_min: 10,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Endurance Day Long Steady State',
    category: 'wod_combination',
    difficulty: 'intermediate',
    description: 'Endurance Day Long Steady State 60min Zone 2 aerobic base building',
    primary_muscles: ['quadriceps', 'mollets'],
    secondary_muscles: ['fessiers', 'ischio-jambiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
];

async function main() {
  console.log('🔀 Seeding Functional WOD Combinations (41 exercises)...\n');

  let success = 0;
  let failed = 0;

  for (const ex of wodCombinations) {
    try {
      await seedExercise(ex);
      success++;
    } catch (error) {
      console.error(`❌ Failed to seed ${ex.name}:`, error);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success}/${wodCombinations.length}`);
  console.log(`❌ Failed: ${failed}/${wodCombinations.length}`);
  console.log('\n🎯 WOD Combinations enrichment complete!');
}

main().then(() => process.exit(0));
