import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const muscleCache = new Map<string, string>();
const equipmentCache = new Map<string, string>();

async function getMuscleId(name: string): Promise<string | null> {
  if (muscleCache.has(name)) return muscleCache.get(name)!;
  const { data } = await supabase.from('muscle_groups').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) muscleCache.set(name, data.id);
  return data?.id || null;
}

async function getEquipmentId(name: string): Promise<string | null> {
  if (equipmentCache.has(name)) return equipmentCache.get(name)!;
  const { data } = await supabase.from('equipment_types').select('id').ilike('name', `%${name}%`).limit(1).maybeSingle();
  if (data) equipmentCache.set(name, data.id);
  return data?.id || null;
}

async function seedExercise(ex: any) {
  const primaryMuscleIds = (await Promise.all((ex.primary_muscles || []).map(getMuscleId))).filter(Boolean);
  const secondaryMuscleIds = (await Promise.all((ex.secondary_muscles || []).map(getMuscleId))).filter(Boolean);
  const equipmentIds = (await Promise.all((ex.equipment || []).map(getEquipmentId))).filter(Boolean);

  const { data: exercise, error } = await supabase.from('exercises').insert({
    name: ex.name,
    discipline: 'endurance',
    category: ex.category,
    difficulty: ex.difficulty,
    description_short: ex.description,
    movement_pattern: ex.movement_pattern || 'cardio',
    is_validated: true,
    typical_sets_min: ex.sets_min || 1,
    typical_sets_max: ex.sets_max || 1,
    typical_reps_min: ex.reps_min || 1,
    typical_reps_max: ex.reps_max || 1,
    typical_rest_sec: ex.rest_sec || 60,
  }).select().single();

  if (error) {
    console.error(`Error inserting ${ex.name}:`, error.message);
    return;
  }

  if (!exercise) return;

  if (primaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      primaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'primary' }))
    );
  }

  if (secondaryMuscleIds.length > 0) {
    await supabase.from('exercise_muscle_groups').insert(
      secondaryMuscleIds.map(id => ({ exercise_id: exercise.id, muscle_group_id: id, involvement_type: 'secondary' }))
    );
  }

  if (equipmentIds.length > 0) {
    await supabase.from('exercise_equipment').insert(
      equipmentIds.map(id => ({ exercise_id: exercise.id, equipment_type_id: id, is_required: true }))
    );
  }

  console.log(`✅ ${ex.name}`);
}

const runningExercises = [
  {
    name: 'Easy Run Zone 1 Recovery',
    category: 'running',
    difficulty: 'beginner',
    description: 'Course facile Z1 récupération active 60-70% FCmax',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Base Run Zone 2 Aerobic',
    category: 'running',
    difficulty: 'beginner',
    description: 'Course base Z2 aérobie 70-80% FCmax allure conversationnelle',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Tempo Run Zone 3',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Course tempo Z3 80-87% FCmax allure soutenue confortable',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Threshold Run Zone 4',
    category: 'running',
    difficulty: 'advanced',
    description: 'Course seuil Z4 87-92% FCmax allure seuil lactique',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'VO2max Intervals Zone 5',
    category: 'running',
    difficulty: 'advanced',
    description: 'Intervalles VO2max Z5 92-100% FCmax effort maximal',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: '200m Repeats Fast',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 200m allure 800m 1:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: '200m Repeats VO2max',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 200m allure VO2max 1:2 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 10,
    sets_max: 16,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 90,
  },
  {
    name: '400m Repeats Threshold',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 400m allure seuil 2:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: '400m Repeats VO2max',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 400m allure VO2max 1:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 90,
  },
  {
    name: '400m Repeats Fast',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 400m allure 1500m 1:3 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: '800m Repeats Threshold',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 800m allure seuil 1:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: '800m Repeats VO2max',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 800m allure VO2max 1:2 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 5,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: '800m Repeats 5K Pace',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Répétitions 800m allure 5K 2:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 6,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 150,
  },
  {
    name: '1000m Repeats Threshold',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 1000m allure seuil lactique',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: '1000m Repeats VO2max',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 1000m allure VO2max 1:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 5,
    sets_max: 7,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: '1200m Repeats Threshold',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 1200m allure seuil 3:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: '1600m Repeats Threshold',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions 1600m mile allure seuil',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 3,
    sets_max: 5,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 300,
  },
  {
    name: '1600m Repeats 10K Pace',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Répétitions 1600m allure 10K 2:1 rest ratio',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'Fartlek Structured 1min-2min-3min',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Fartlek structuré pyramide 1-2-3-2-1min Z4-Z5',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 2,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Fartlek Unstructured Nature Run',
    category: 'running',
    difficulty: 'beginner',
    description: 'Fartlek libre selon terrain et sensation Z2-Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Hill Repeats Short 30sec',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions côtes courtes 30sec max effort',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 8,
    sets_max: 12,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Hill Repeats Medium 90sec',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions côtes moyennes 90sec Z4-Z5',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Hill Repeats Long 3min',
    category: 'running',
    difficulty: 'advanced',
    description: 'Répétitions côtes longues 3min Z4 threshold',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 240,
  },
  {
    name: 'Progression Run 10K',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Course progression 10K Z2→Z3→Z4 negative split',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Progression Run Half Marathon',
    category: 'running',
    difficulty: 'advanced',
    description: 'Course progression 21K Z2→Z3 finish Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Long Run Zone 2 Endurance',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Sortie longue Z2 base aérobie endurance fondamentale',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Marathon Pace Run',
    category: 'running',
    difficulty: 'advanced',
    description: 'Course allure marathon Z3 tempo soutenu',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Yasso 800s Workout',
    category: 'running',
    difficulty: 'advanced',
    description: 'Yasso 800s pour prédiction marathon 800m répétitions',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Kenyan Hills Workout',
    category: 'running',
    difficulty: 'advanced',
    description: 'Kenyan hills course côtes continues Z3-Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Track 5K Time Trial',
    category: 'running',
    difficulty: 'advanced',
    description: 'Test 5K piste allure compétition Z4-Z5',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Track 10K Time Trial',
    category: 'running',
    difficulty: 'advanced',
    description: 'Test 10K piste allure compétition Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Cruise Intervals 5min',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Intervalles cruise 5min allure seuil 1min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 6,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Cruise Intervals 10min',
    category: 'running',
    difficulty: 'advanced',
    description: 'Intervalles cruise 10min allure seuil 2min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 3,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Strides 100m Acceleration',
    category: 'running',
    difficulty: 'beginner',
    description: 'Lignes droites 100m accélérations progressives',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 6,
    sets_max: 10,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 60,
  },
  {
    name: 'Recovery Run 30min Zone 1',
    category: 'running',
    difficulty: 'beginner',
    description: 'Course récupération 30min Z1 très facile',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Tempo Run 20min Threshold',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Tempo 20min allure seuil lactique Z4',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Lactate Threshold Test 30min',
    category: 'running',
    difficulty: 'advanced',
    description: 'Test seuil lactique 30min max effort soutenu',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: '3-2-1 Intervals Pyramid',
    category: 'running',
    difficulty: 'advanced',
    description: 'Pyramide 3min-2min-1min Z5 avec repos égaux',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 2,
    sets_max: 3,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: '4x4min VO2max Intervals',
    category: 'running',
    difficulty: 'advanced',
    description: '4x4min Z5 VO2max intervalles norvégiens 3min repos',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 4,
    sets_max: 4,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 180,
  },
  {
    name: 'Tabata Running 20-10',
    category: 'running',
    difficulty: 'advanced',
    description: 'Tabata course 20sec sprint 10sec repos 8 rounds',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 8,
    sets_max: 8,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 10,
  },
  {
    name: '30-30 Intervals Billat',
    category: 'running',
    difficulty: 'advanced',
    description: '30-30 Billat 30sec Z5 30sec récup répétitions',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 10,
    sets_max: 20,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 30,
  },
  {
    name: 'Tempo Sandwich Run',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Sandwich tempo Z2-Z4-Z2 échauffement-bloc-retour',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Cutdown Run Descending',
    category: 'running',
    difficulty: 'advanced',
    description: 'Course cutdown allure descendante 1600-1200-800-400',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 120,
  },
  {
    name: 'Magic Mile Test',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Test Magic Mile 1600m pour prédiction courses',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Cooper Test 12min',
    category: 'running',
    difficulty: 'advanced',
    description: 'Test Cooper 12min distance maximale VO2max',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Negative Split Long Run',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Sortie longue negative split 2ème moitié plus rapide',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Trail Run Technical Terrain',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Course trail terrain technique Z2-Z3 montée-descente',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Uphill Tempo 20min',
    category: 'running',
    difficulty: 'advanced',
    description: 'Tempo montée continue 20min Z4 effort soutenu',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets', 'fessiers'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
  {
    name: 'Downhill Running Eccentric',
    category: 'running',
    difficulty: 'intermediate',
    description: 'Course descente contrôlée renforcement excentrique',
    primary_muscles: ['quadriceps', 'ischio-jambiers', 'mollets'],
    equipment: [],
    sets_min: 1,
    sets_max: 1,
    reps_min: 1,
    reps_max: 1,
    rest_sec: 0,
  },
];

async function main() {
  console.log('🏃 Seeding Endurance Running Zones & Intervals (50 exercises)...\n');

  let success = 0;
  let failed = 0;

  for (const ex of runningExercises) {
    try {
      await seedExercise(ex);
      success++;
    } catch (error) {
      console.error(`❌ Failed to seed ${ex.name}:`, error);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success}/${runningExercises.length}`);
  console.log(`❌ Failed: ${failed}/${runningExercises.length}`);
  console.log('\n🎯 Running zones & intervals enrichment complete!');
}

main().then(() => process.exit(0));
