/*
  # Create recipe-images storage bucket

  1. Storage Bucket
    - Creates `recipe-images` bucket for storing AI-generated recipe images
    - Permanent storage for images generated by GPT-image-1
    - Replaces temporary OpenAI URLs that expire after 60 minutes

  2. Security
    - Public bucket for easy access to recipe images
    - RLS policies for authenticated users to upload
    - Anyone can read images (public recipes)

  3. Important Notes
    - Images are organized in /recipes/ folder
    - Filename format: recipe-{recipe_id}-{timestamp}.png
    - Used by image-generator edge function
*/

-- Create the recipe-images storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('recipe-images', 'recipe-images', true)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to upload images
CREATE POLICY "Authenticated users can upload recipe images"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'recipe-images');

-- Allow authenticated users to update their own images
CREATE POLICY "Authenticated users can update recipe images"
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (bucket_id = 'recipe-images');

-- Allow anyone to read recipe images (public bucket)
CREATE POLICY "Anyone can view recipe images"
  ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'recipe-images');

-- Allow authenticated users to delete recipe images
CREATE POLICY "Authenticated users can delete recipe images"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id = 'recipe-images');
